# Generated by Django 5.0.6 on 2026-05-29 19:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(max_length=50)),
                ('color', models.CharField(help_text="Tailwind color name, e.g. 'blue'", max_length=20)),
                ('primary_hex', models.CharField(default='#1d4ed8', max_length=7)),
                ('secondary_hex', models.CharField(default='#0b1d50', max_length=7)),
                ('flag_emoji', models.CharField(default='🏳️', max_length=8)),
                ('total_points', models.IntegerField(default=0)),
                ('entry_rank', models.IntegerField(blank=True, help_text='Auto-assigned rank when all members have arrived for hall entry.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'خدمة'), ('play', 'لعب'), ('retreat', 'خلوة')], max_length=20)),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('is_entry', models.BooleanField(default=False, help_text="True for the activity that represents 'دخول القاعة' (used for entry-ranking logic).")),
                ('is_active', models.BooleanField(default=False, help_text='The single activity currently being used on the live screen and scanner.')),
            ],
            options={
                'ordering': ['kind', 'number'],
                'unique_together': {('kind', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unique_code', models.CharField(max_length=32, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.team')),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('on_time', 'حضر في المعاد'), ('late', 'اتأخر'), ('absent', 'غاب')], max_length=12)),
                ('bonus_points', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('scanned_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.activity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.participant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'activity')},
            },
        ),
    ]
