# Generated by Django 5.0.6 on 2026-05-29 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='entry_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completion_order', models.JSONField(blank=True, default=list)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.activity')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
