# Generated by Django 5.0.6 on 2026-06-02 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_is_active_alter_activity_is_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(default=1)),
                ('session_type', models.CharField(choices=[('individual', 'فردي'), ('team', 'فريق')], default='individual', max_length=12)),
                ('location', models.CharField(blank=True, choices=[('qa3a_1', 'قاعة 1'), ('qa3a_2', 'قاعة 2'), ('qa3a_3', 'قاعة 3'), ('qa3a_4', 'قاعة 4'), ('qa3a_5', 'قاعة 5'), ('qa3a_6', 'قاعة 6'), ('mal3ab_1', 'ملعب 1'), ('mal3ab_2', 'ملعب 2'), ('mal3ab_3', 'ملعب 3'), ('mal3ab_4', 'ملعب 4'), ('mal3ab_5', 'ملعب 5')], max_length=20)),
                ('scanned_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='core.participant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
